title: Network Problems
description: My Personal Network
author: He Zhidong
github: https://github.com/zhidonghe
about: I'm Researcher for Networks.
disqus_shortname: mynetworks
google_analytics: UXXXXXXXX

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: github.io
  fb_appid: "#"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://zhidonghe.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
